apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cal-results-pvc
  namespace: vramani-perfcal
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ibm-spectrum-scale-fileset
  resources:
    requests:
      storage: 50Gi
